### ISSUE TITLE
ES Lint GitHub action not working

### ISSUE THREAD

**Issue by toniengelhardt** [toniengelhardt/m3tadata#2]
The idea is to test the build and have basic linting and type-checking in the CI pipe, but all jobs fail with

<img width="589" alt="Screenshot 2022-12-29 at 20 19 52" src="https://user-images.githubusercontent.com/2703233/210007462-a5ea36af-c6c5-4372-a339-b8c8085082c7.png">

**Comment by RyanPaulGannon** [comment]
Don't know a great deal about this so I may be way off, but the red cross has been driving me nuts ha! 

When I looked at the `eslint.yml` file, on line 35: `npm install eslint@8.28.0` but when I've looked at the `package.json`, the `devDependencies` version is `"eslint": "^8.29.0"`.

Could this be the issue?

**Comment by toniengelhardt** [comment]
It's not so easy unfortunately. I copied the script from somewhere but apparently it doesn't work out of the box with pnpm. I played around a bit but couldn't make it work. Turned it off for now to avoid the red cross.

**Comment by RyanPaulGannon** [comment]
I thought it seemed too simple to be true, never mind. We can always look at it passively in the meantime.

**Comment by toniengelhardt** [comment]
Yes, and try to copy from somewhere else lol, e.g. nuxt/framework itself.

**Comment by toniengelhardt** [comment]
Resolved. The issue was a bug in the latest version of pnpm.
